# Generated by Django 3.1 on 2020-09-18 11:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='վերնագիր')),
                ('img', models.ImageField(upload_to='', verbose_name='նկար')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='տեքստ')),
            ],
            options={
                'verbose_name': 'արտադրանք',
                'verbose_name_plural': 'արտադրանքներ',
            },
        ),
        migrations.CreateModel(
            name='Subscribe_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256, verbose_name='Էլ․ փոստ')),
            ],
            options={
                'verbose_name': 'Էլ․ փոստի բաժանորդագրություն',
                'verbose_name_plural': 'Էլ․ փոստի բաժանորդագրություններ',
            },
        ),
    ]
