# Generated by Django 3.1 on 2020-09-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=256, verbose_name='տիպ')),
            ],
            options={
                'verbose_name': 'տիպ',
                'verbose_name_plural': 'տիպեր',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='նկար')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.type', verbose_name='տիպ')),
            ],
            options={
                'verbose_name': 'Օրինակ',
                'verbose_name_plural': 'Օրինակներ',
            },
        ),
    ]
